---
  - name: Include vars
    include_vars: main.yml

  - name: Install PostgreSQL repo
    yum:
      name: "{{ postgresql_rpm_6 }}"
      state: present
      validate_certs: no
    when: ansible_distribution_major_version == "6"

  - name: Install PostgreSQL repo
    yum:
      name: "{{ postgresql_rpm_7 }}"
      state: present
    when: ansible_distribution_major_version == "7"

  - name: PostgreSQL | Install PostgreSQL 
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - postgresql95-server
      - postgresql95
      - postgresql95-libs
      - postgresql95-devel
      - postgresql95-contrib
      - python-psycopg2
      - libselinux-python
    register: new_installation

#  - name: Install repmgr --CentOS 6
#    yum: name="{{ repmgr_rpm_6 }}" state=present
#    when: ansible_distribution_major_version == "6"

#  - name: Install repmgr --CentOS 7
#    yum: name="{{ repmgr_rpm_7 }}" state=present
#    when: ansible_distribution_major_version == "7"
     
#  - name: Create repmgr path to config 
#    file:
#      path: "{{ item }}"
#      state: directory
#      owner: postgres
#      group: postgres
#    with_items:
#      - "/var/lib/pgsql/repmgr"

  - name: Initiate database ---  MASTER DB
    command: /usr/pgsql-9.5/bin/initdb -d /var/lib/pgsql/9.5/data/
    args:
        creates: /var/lib/pgsql/9.5/data/postgresql.conf
    when: new_installation.changed


  - name: Restart postgresql-9.5
    service:
      name: postgresql-9.5
      state: restarted

  - name: Insert dat into pg_hba.conf 
    template:
      src: pg_hba.conf.j2
      dest: /var/lib/pgsql/9.5/data/pg_hba.conf
      owner: postgres
      group: postgres
 
  - name: Restart postgresql-9.5
    service: 
      name: postgresql-9.5
      state: restarted 
 
  - name: Start PostgreSQL and enable at boot 
    service:
      name: postgresql-9.5
      enabled: yes
      state: started

  - name: Create DB user
    become_user: postgres
    become: yes
    postgresql_user:
      name: "{{ DB_user }}"
      password: "{ DB_pass }}"
      role_attr_flags: SUPERUSER # needs for repmgr
      state: present

  - name: Restart postgresql-9.5
    service: 
      name: postgresql-9.5
      state: restarted

  - name: Create DB 
    become_user: postgres
    become: yes
    postgresql_db:
      name: "{{ DB_name }}"
      owner: "{{ DB_user }}"
      encoding: 'UTF-8'
      lc_collate: 'en_US.UTF-8'
      lc_ctype: 'en_US.UTF-8'
      template: 'template0'
      state: present

  - name: Restart postgresql-9.5
    service: 
      name: postgresql-9.5
      state: restarted

  - name: Set connection limit.
    lineinfile:
      dest: /var/lib/pgsql/9.5/data/postgresql.conf
      regexp: '^max_connections'
      line: 'max_connections = 1000'   

  - name: ReStart PostgreSQL 
    service:
      name: postgresql-9.5
      state: restarted

  - name: Disable selinux
    selinux:
      state: disabled
    register: was_enabled

  - shell: setenforce 0
    sudo: yes
    ignore_errors: True
    when: was_enabled.changed
      


