---
  - name: Install repository
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
      - "http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"

  - name: Install Nagios packages
    yum: 
      name: "{{ item }}"
      state: present
    with_items:
      - nagios
      - nagios-plugins-all
      - nrpe
      - libselinux-python

  - name: Copy configuration file
    template:
      src: nrpe.cfg.j2
      dest: /etc/nagios/nrpe.cfg

  - name: Start Nagios client
    service:
      name: nrpe
      state: restarted
      enabled: yes
