---
  - name: Install repository
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
      - "http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"

  - name: Install Nagios packages
    yum: 
      name: "{{ item }}"
      state: present
    with_items:
      - nagios
      - nagios-plugins-all
      - nrpe
      - libselinux-python

  - name: Copy configuration file
    template:
      src: nrpe.cfg.j2
      dest: /etc/nagios/nrpe.cfg

  - name: Add http index file
    file:
      path: /var/www/html/index.html
      state: touch
      mode: 0755

  - name: Add sudo rights for nrpe
    blockinfile:
      path: /etc/sudoers
      block: |
       ## Allow NRPE to restart sevices
       Defaults:nagios !requiretty
       nagios    ALL=(ALL)    NOPASSWD: /sbin/service 

  - name: Disable selinux
    selinux:
      state: disabled
    register: was_enabled

  - shell: setenforce 0
    sudo: yes
    ignore_errors: True
    when: was_enabled.changed


  - name: Start Nagios client
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - nrpe
      - httpd


