DB_root_user: "root"
DB_root_pass: "1q2w3e4r5t"
remove_installed: "1"
DB_host: "localhost"
DB_name: "zabbixdb"
DB_user: "zabbixuser"
DB_pass: "1q2w3e"
postgresql_rpm_6: "https://yum.postgresql.org/9.5/redhat/rhel-6.9-x86_64/pgdg-centos95-9.5-2.noarch.rpm"
postgresql_rpm_7: "https://yum.postgresql.org/9.5/redhat/rhel-7.3-x86_64/pgdg-centos95-9.5-2.noarch.rpm"
repmgr_rpm_6: "https://yum.postgresql.org/9.5/redhat/rhel-6.9-x86_64/repmgr95-3.3.1-1.hel6.x86_64.rpm"
repmgr_rpm_7: "https://yum.postgresql.org/9.5/redhat/rhel-7.3-x86_64/repmgr95-3.3.1-1.rhel7.x86_64.rpm"
